- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  community.routeros.api_facts: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: 'yes'
      update_cache: yes
      cache_valid_time: 86400 
    when: ansible_os_family == "Debian"
  - name: Upgrade RHEL Family OS packages
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"
  - name: set routeros firmware channel
#    routeros_command:
#      commands:
#        - /system package update set channel=stable
#  - name: upgrade packages and reboot
#    routeros_command:
#      commands:
#        - /system package update install
