---
- name: Install Apache Tomcat and Deploy App
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: default-jdk
        state: present

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: directory

    - name: Download & unarchive Tomcat
      unarchive:
        src: "https://{{ auser }}:{{ apass }}@{{ nexus }}/repository/maven-releases/install/apache-tomcat/9.0.93/apache-tomcat-9.0.93.tar.gz"
        dest: /opt/tomcat
        remote_src: yes
        owner: tomcat
        group: tomcat
        mode: '0640'
        extra_opts: [--strip-components=1]

    - name: Tomcat Config
      unarchive:
        src: "https://{{ auser }}:{{ apass }}@{{ nexus }}/repository/maven-releases/config/tomcat-conf/1.0/tomcat-conf-1.0.zip"
        dest: /opt/tomcat/conf
        remote_src: yes
        owner: tomcat
        group: tomcat

    - name: Delete application WAR
      file:
        state: absent
        path: /opt/tomcat/webapps/speedtest.war

    - name: Clean up app work and temp folders
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /opt/tomcat/work/
        - /opt/tomcat/temp/

    - name: Download & Deploy app from Nexus repo
      maven_artifact:
        group_id: "fr.cedrik.speedtest"
        artifact_id: "speedtest"
        version: "latest"
        extension: "war"
        repository_url: "https://{{ nexus }}/repository/maven-releases/"
        username: "{{ auser }}"
        password: "{{ apass }}"
        validate_certs: true
        dest: /opt/tomcat/webapps/speedtest.war
        mode: '0640'
        owner: tomcat
        group: tomcat

    - name: Change ownership of Tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: '0755'

    - name: Start and Enable Tomcat on server
      systemd:
        name: tomcat
        state: restarted
        daemon_reload: true
