- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - name: Install all security updates with automatic reboots
    connection: winrm
    win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      reboot: yes
    when: ansible_os_family == "Windows"

  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: 'yes'
      update_cache: yes
      cache_valid_time: 86400 
    when: ansible_os_family == "Debian"
  - name: Upgrade RHEL Family OS packages
    become: yes
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"
#  - name: set routeros firmware channel
#    routeros_command:
#      commands:
#        - /system package update set channel=stable
#  - name: upgrade packages and reboot
#    routeros_command:
#      commands:
#        - /system package update install
