- hosts: all
#  serial: 1
  strategy: free
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - name: Install all security updates with automatic reboots
    connection: winrm
    win_updates:
      category_names: '*'
#      - SecurityUpdates
#      - CriticalUpdates
#      - UpdateRollups
      reboot: yes
    when: ansible_os_family == "Windows"

  - block:
      - name: Update and upgrade apt packages
        become: yes
        apt:
          upgrade: 'yes'
          update_cache: yes
          cache_valid_time: 86400
#      - name: Update and upgrade apt packages
#        become: yes
#        apt:
#          autoclean: yes
#          autoremove: yes
#          purge: true
#          clean: yes
    when: ansible_os_family == "Debian"

  - block:
      - name: Upgrade RHEL Family OS packages
        become: yes
        yum:
          name: '*'
          state: latest
      - name: yum clean all
        command: yum clean all
        args:
          warn: false
    when: ansible_os_family == "RedHat"
